import type { jsPDF } from "jspdf";
import type { CashbookProfile } from "./profile";
import { currencyPrefix } from "./profile";

export type CashReportRow = {
  id: number;
  date: string;
  time: string;
  description: string;
  direction: "IN" | "OUT";
  amount: number;
  walletId: string;
  source: string;
};

const money = (value:number,currency:CashbookProfile["currency"]) => `${currencyPrefix(currency)} ${value.toLocaleString("en-PK")}`;
const displayDate = (value:string) => new Date(`${value}T12:00:00`).toLocaleDateString("en-PK",{day:"numeric",month:"short",year:"numeric"});

export async function createCashReportPdf(rows:CashReportRow[],profile:CashbookProfile,walletNames:Record<string,string>,from:string,to:string){
  const {jsPDF}=await import("jspdf");const doc=new jsPDF({unit:"mm",format:"a4"});let y=0;
  const header=()=>{doc.setFillColor(29,27,24);doc.rect(0,0,210,31,"F");doc.setTextColor(255,255,255);doc.setFont("helvetica","bold");doc.setFontSize(18);doc.text("Hisaab - Cash In & Out Report",14,14);doc.setFont("helvetica","normal");doc.setFontSize(10);doc.text(`${displayDate(from)} to ${displayDate(to)}`,14,23);doc.text(`Page ${doc.getNumberOfPages()}`,194,23,{align:"right"});doc.setTextColor(35,33,30);y=41};
  const page=(needed=12)=>{if(y+needed<282)return;doc.addPage();header()};header();
  const moneyIn=rows.filter(r=>r.direction==="IN").reduce((s,r)=>s+r.amount,0);const moneyOut=rows.filter(r=>r.direction==="OUT").reduce((s,r)=>s+r.amount,0);
  [["MONEY IN",moneyIn],["MONEY OUT",moneyOut],["NET",moneyIn-moneyOut]].forEach(([label,value],i)=>{const x=14+i*61;doc.setFillColor(i===2?255:247,i===2?241:245,i===2?235:241);doc.roundedRect(x,y,57,22,3,3,"F");doc.setFontSize(8);doc.setTextColor(110,104,96);doc.text(String(label),x+4,y+7);doc.setFont("helvetica","bold");doc.setFontSize(12);doc.setTextColor(35,33,30);doc.text(money(Number(value),profile.currency),x+4,y+16);doc.setFont("helvetica","normal")});y+=31;
  doc.setFillColor(235,231,224);doc.rect(14,y,182,9,"F");doc.setFontSize(8);["Date","Description","Wallet","In","Out"].forEach((label,i)=>doc.text(label,[16,43,116,151,176][i],y+6));y+=9;
  [...rows].sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id).forEach(row=>{page();doc.setFontSize(8);doc.text(displayDate(row.date),16,y+6);doc.text(row.description.slice(0,38),43,y+6);doc.text((walletNames[row.walletId]||"Wallet").slice(0,16),116,y+6);if(row.direction==="IN")doc.text(money(row.amount,profile.currency),151,y+6);else doc.text(money(row.amount,profile.currency),176,y+6);doc.setDrawColor(232,228,222);doc.line(14,y+9,196,y+9);y+=10});
  if(!rows.length){doc.setTextColor(110,104,96);doc.text("No cash entries in this date range.",16,y+9)}
  doc.setFontSize(7);doc.setTextColor(110,104,96);doc.text(`Generated by Hisaab on ${new Date().toLocaleDateString("en-PK")}`,105,290,{align:"center"});
  return {doc,filename:`cash-report-${from}-to-${to}.pdf`};
}

export function cashReportCsv(rows:CashReportRow[],walletNames:Record<string,string>){
  const escape=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;
  return [["Date","Time","Wallet","Description","Money In","Money Out","Source"],...rows.map(r=>[r.date,r.time,walletNames[r.walletId]||"Wallet",r.description,r.direction==="IN"?r.amount:"",r.direction==="OUT"?r.amount:"",r.source])].map(row=>row.map(escape).join(",")).join("\n");
}
