import type { jsPDF } from "jspdf";
import type { CashbookProfile } from "./profile";
import { currencyPrefix } from "./profile";
import type { InstallmentScheduleRow, PersonLedger, PersonLedgerEntry } from "./planning";
import { installmentSchedule, ledgerOutstanding, ledgerPrincipal, ledgerReceived } from "./planning";

const safeName = (value: string) => value.trim().replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "") || "ledger";
const money = (value: number, currency: CashbookProfile["currency"]) => `${currencyPrefix(currency)} ${value.toLocaleString("en-PK")}`;
const displayDate = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString("en-PK", { day: "numeric", month: "short", year: "numeric" });

function addPageHeader(doc: jsPDF, ledger: PersonLedger, page: number) {
  doc.setFillColor(29, 27, 24);
  doc.rect(0, 0, 210, 31, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Hisaab - Receivable Ledger", 14, 14);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`${ledger.personName}${ledger.relation ? ` - ${ledger.relation}` : ""}`, 14, 23);
  doc.text(`Page ${page}`, 194, 23, { align: "right" });
  doc.setTextColor(35, 33, 30);
}

function ensurePage(doc: jsPDF, ledger: PersonLedger, y: number, needed = 15) {
  if (y + needed < 282) return y;
  doc.addPage();
  addPageHeader(doc, ledger, doc.getNumberOfPages());
  return 41;
}

export async function createLedgerPdf(ledger: PersonLedger, entries: PersonLedgerEntry[], profile: CashbookProfile, walletNames: Record<string, string>) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  addPageHeader(doc, ledger, 1);
  const principal = ledgerPrincipal(ledger, entries);
  const received = ledgerReceived(entries, ledger.id);
  const outstanding = ledgerOutstanding(ledger, entries);
  let y = 41;
  const cards = [
    ["Total receivable", money(principal, profile.currency)],
    ["Received", money(received, profile.currency)],
    ["Outstanding", money(outstanding, profile.currency)],
  ];
  cards.forEach(([label, value], index) => {
    const x = 14 + (index * 61);
    doc.setFillColor(index === 2 ? 255 : 247, index === 2 ? 241 : 245, index === 2 ? 235 : 241);
    doc.roundedRect(x, y, 57, 23, 3, 3, "F");
    doc.setFontSize(8);
    doc.setTextColor(110, 104, 96);
    doc.text(label.toUpperCase(), x + 4, y + 7);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(35, 33, 30);
    doc.text(value, x + 4, y + 16);
    doc.setFont("helvetica", "normal");
  });
  y += 33;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Ledger activity", 14, y);
  y += 7;
  doc.setFillColor(235, 231, 224);
  doc.rect(14, y, 182, 9, "F");
  doc.setFontSize(8);
  ["Date", "Details", "Wallet", "Given", "Received", "Balance"].forEach((label, index) => doc.text(label, [16, 39, 99, 130, 151, 176][index], y + 6));
  y += 9;
  let balance = ledger.openingReceivable;
  const rows = [...entries].filter((entry) => entry.ledgerId === ledger.id).sort((a, b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id));
  if (ledger.openingReceivable > 0) {
    doc.setFontSize(8);
    doc.text("Opening", 16, y + 6);
    doc.text("Opening receivable", 39, y + 6);
    doc.text(money(ledger.openingReceivable, profile.currency), 176, y + 6);
    y += 9;
  }
  rows.forEach((entry) => {
    y = ensurePage(doc, ledger, y, 11);
    balance += entry.kind === "RECEIVED" ? -entry.amount : entry.amount;
    doc.setDrawColor(232, 228, 222);
    doc.line(14, y + 9, 196, y + 9);
    doc.setFontSize(8);
    doc.text(displayDate(entry.date), 16, y + 6);
    doc.text((entry.note || (entry.kind === "RECEIVED" ? "Installment received" : "Money given")).slice(0, 35), 39, y + 6);
    doc.text((entry.walletId ? walletNames[entry.walletId] : "-")?.slice(0, 16) || "-", 99, y + 6);
    if (entry.kind !== "RECEIVED") doc.text(money(entry.amount, profile.currency), 130, y + 6);
    if (entry.kind === "RECEIVED") doc.text(money(entry.amount, profile.currency), 151, y + 6);
    doc.text(money(balance, profile.currency), 176, y + 6);
    y += 10;
  });
  if (!rows.length && !ledger.openingReceivable) {
    doc.setFontSize(9);
    doc.setTextColor(110, 104, 96);
    doc.text("No ledger activity recorded yet.", 16, y + 8);
    y += 14;
  }
  const schedule = installmentSchedule(ledger, entries);
  if (schedule.length) y = addSchedule(doc, ledger, schedule, profile, y + 8);
  y = ensurePage(doc, ledger, y + 8, 24);
  doc.setDrawColor(211, 205, 197);
  doc.line(14, y, 82, y);
  doc.line(128, y, 196, y);
  doc.setFontSize(8);
  doc.setTextColor(110, 104, 96);
  doc.text("Lender signature", 14, y + 5);
  doc.text("Borrower signature", 128, y + 5);
  doc.setFontSize(7);
  doc.text(`Generated by Hisaab on ${new Date().toLocaleDateString("en-PK")}`, 105, 290, { align: "center" });
  return { doc, filename: `${safeName(ledger.personName)}-receivable-ledger.pdf` };
}

function addSchedule(doc: jsPDF, ledger: PersonLedger, schedule: InstallmentScheduleRow[], profile: CashbookProfile, initialY: number) {
  let y = ensurePage(doc, ledger, initialY, 25);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(35, 33, 30);
  doc.setFontSize(12);
  doc.text("Monthly installment schedule", 14, y);
  y += 7;
  schedule.forEach((row) => {
    y = ensurePage(doc, ledger, y, 10);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(50, 47, 43);
    doc.text(`#${row.number}`, 16, y + 5);
    doc.text(displayDate(row.dueDate), 32, y + 5);
    doc.text(money(row.amount, profile.currency), 91, y + 5);
    doc.text(row.paid ? `${money(row.paid, profile.currency)} paid` : "-", 127, y + 5);
    doc.text(row.status, 190, y + 5, { align: "right" });
    doc.setDrawColor(232, 228, 222);
    doc.line(14, y + 8, 196, y + 8);
    y += 9;
  });
  return y;
}

export function ledgerPdfFile(doc: jsPDF, filename: string) {
  const blob = doc.output("blob");
  return new File([blob], filename, { type: "application/pdf" });
}
